version: '3'

services:
  postgres:
    image: postgres:14-alpine3.14
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - '5432:5432'
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    ports:
      - '3306:3306'
