name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Fetch pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip
    - name: Install dependencies
      run: |
        pip install yapf
    - name: Analyzing the code
      run: |
        yapf -dpr secured_fields test_secured_fields

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
        django: ["3.0", "3.1", "3.2"]
        # ref: https://github.com/jefftriplett/python-github-actions-matrix-demo
        exclude:
          # Python 3.9 is compatible with Django 3.1+, Django REST 3.12+
          - python: "3.9"
            django: "3.0"
          # Python 3.10 is compatible with Django 3.2+
          - python: "3.10"
            django: "3.0"
          - python: "3.10"
            django: "3.1"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Fetch pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ matrix.python }}
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: /home/runner/.cache/pypoetry/virtualenvs
          key: venv-${{ matrix.python }}-${{ matrix.django }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.12"
      - name: Install dependencies
        run: |
          poetry install -n
          poetry run pip install --no-input django~=${{ matrix.django }}.0
      - name: Verify package versions
        run: |
          python -V
          poetry show django
      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: tests.settings
        run: |
          python manage.py test
