name: Build & Publish to PyPi

on:
  push:
    tags: [ v* ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Fetch pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip
    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: "1.1.12"
    - name: Install publishing tools
      run: |
        pip install poetry-dynamic-versioning[plugin]
    - name: Build and publish package
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry publish -n --build
    - name: Create GitHub release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        generateReleaseNotes: true
