name: Build & Publish to PyPi

on:
  push:
    tags: [ v* ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.13"
    - name: Fetch pip cache
      uses: actions/cache@v6
      with:
        path: ~/.cache/pip
        key: pip
    - name: Install Poetry
      run: |
        pipx install --python "$(which python)" poetry==2.3.3
        pipx inject poetry poetry-dynamic-versioning
    - name: Build and publish package
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry publish -n --build
    - name: Create GitHub release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        generateReleaseNotes: true
